logsBucket: gs://gcp_cloud_build_test
steps:

  - name: 'test-allwin/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'
  - name: 'test-allwin/cloud-builders/docker'
    args: ['build', '-t', 'test-allwin/sandbox-427408/gcloud-build-test-img:tag', '.']
    dir: '.'
  - name: 'test-allwin/cloud-builders/docker'
    args: ['push', 'test-allwin/sandbox-427408/gcloud-build-test-img:tag']

serviceAccount: sandbox-427408@appspot.gserviceaccount.com