#logsBucket: gs://gcp_cloud_build_test
#steps:
#
#  - name: 'gcr.io/cloud-builders/mvn'
#    args: ['clean', 'package']
#    dir: '.'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['build', '-t', 'gcr.io/sandbox-427408/gcloud-build-test-img:tag', '.']
#    dir: '.'
#  - name: 'gcr.io/cloud-builders/docker'
#    args: ['push', 'gcr.io/sandbox-427408/gcloud-build-test-img:tag']
#
#serviceAccount: sandbox-427408@appspot.gserviceaccount.com


logsBucket: gs://gcp_cloud_build_test

steps:
  - name: 'gcr.io/cloud-builders/mvn'
    args: ['clean', 'package']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'                                                      // to build a docker image in artifact registry
    args: ['build', '-t', 'gcr.io/sandbox-427408/gcloud-build-test-img:$SHORT_SHA', '.']
    dir: '.'

  - name: 'gcr.io/cloud-builders/docker'                                                      // to push the docker image in artifact registry
    args: ['push', 'gcr.io/sandbox-427408/gcloud-build-test-img:$SHORT_SHA']

  - name: 'gcr.io/cloud-builders/gcloud'                                                      // to deploy the docker image in cloud build
    args: [
      'run', 'deploy', 'gcloud-build-test-img',
      '--image', 'gcr.io/sandbox-427408/gcloud-build-test-img:$SHORT_SHA',
      '--platform', 'managed',
      '--region', 'us-central1',
      '--allow-unauthenticated'
    ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'

images:
  - 'gcr.io/sandbox-427408/gcloud-build-test-img:$SHORT_SHA'

serviceAccount: sandbox-427408@appspot.gserviceaccount.com
